### ISSUE TITLE
Docker available

### ISSUE THREAD

**Issue by duffy6** [elbosso/FritzBoxShell#6]
Hi!
Is there a docker container available?

Greetz
Duffy6

**Comment by elbosso** [comment]
Hi, no and there are no plans to do anything "docker" in this project. It came about as a shell script you can execute in any shell or terminal to ask the fritz box for information about itself. Later on there was some documentation added to use it as an extension to telegraf. 
To summarize: This project was always envisioned as an extension of other tools to bridge the gap between said tools and the awkward fritz box monitoring interface. There are of course way more tools than a terminal or telegraf where this script could be bringing some benefit - but I see no connection to docker in any way. Therefore i am closing this Ticket as off-topic and wont-fix. If you feel that your wish for docker support is important and would therefore elaborate upon it and educate me - feel free!
